#Default Parameters needed for a YAML file
openapi: 3.0.0
servers:
  - url: 'https://ndi.sg.io:3035/api/v1' #Real API link
    description: NDI API
    variables: {}
  - url: 'https://sandbox.ndi.io:3031/api/v1' #sandbox API link
    description: NDI API Sandbox
info:
  description: >-
    This is the API store where you can discover everything about integrating
    with the National Digital Identity (NDI) platform.  You can find out more
    about NDI at [http://ndi.sg.io/home](http://ndi.sg.io/home).  To try out the
    API, first go to the Authorization section to learn how to obtain an access
    token to access the API.
  version: 1.0.0
  title: National Digital Identity (NDI) - Domain Authorization
  termsOfService: 'http://ndi.sg.io/terms/'
  contact:
    email: apiteam@ndi.sg.io
  license:
    name: Apache-2.0
    url: 'https://opensource.org/licenses/Apache-2.0'

#These are the tags for the side bar (the one on the left)
tags:
  - name: Domain Authorization Interface
    description: Domain Authorization Interface


paths:
  '/token':
    post:
      tags: 
       - Domain Authorization Interface
      summary: Exchange for an access token from thr authorization service
      description: >-
        This ASP is called by ASP to send a signed challenge (JWS) to the target
        form factor, in the form of an authentication request.
      operationId: exchangeToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  description: The client's ID
                  type: string
                grant_type:
                  description: It must be 'urn:ietf:params:oauth:grant-type:token-exchange
                  type: string
                subject_token:
                  description: The ID token generated by the ASP after a successful user authentication
                  type: string
                subject_token_type:
                  description: It must be 'urn:ietf:params:oauth:token-type:id_token
                  type: string
                scope:
                  description: The scope of access requested
                  type: string
                requested_token_type:
                  description: Set to 'urn:ietf:params:oauth:token-type:access_token' to exchange for an access token
                  type: string
              example:
                client_id: demowapp2
                grant_type: urn:ietf:params:oauth:grant-type:token-exchange
                requested_token_type: urn:ietf:params:oauth:token-type:access_token
                scope: openid
                subject_token: eyJ0eXAiOiJKV1QiLCJraWQiOiIxLjMuNi4xLjQuMS43MjcyMi4zLjEiLCJhbGciOiJFUzI1NiJ9.eyJpc3MiOiJpY2ViZWFyMS5hc3AiLCJzdWIiOiJiNzU1NTI3MC02NTYzLTExZTgtOWNhMS05MWFlNzQwZDZhMDAiLCJhdWQiOiJkZW1vd2FwcDIiLCJkbiI6IndhcHAyLm5kaWRlbW8uY2YiLCJpYXQiOjE1Mjc4MzQxNDQzNTgsImV4cCI6MTUyNzgzNDE0NDk1OCwibm9uY2UiOiIyMDg2Y2JjMC02NTY0LTExZTgtYTE2ZS0wOWNjZGYxNmJkZTEifQ.kwTkW8DKq1PAHNjt4U_GBbCPsmeCSou2u7lNp1S1WoC13EQXxk5xlr4GsCwwQKONBgfbJaqK9vSokmOhRbiAhw
                subject_token_type: urn:ietf:params:oauth:token-type:id_token
                
      responses: 
        '200':
          description: "Success"
          content:
              application/json:
                schema:
                  type: object
                  properties: 
                    access_token:
                        description: The access token
                        type: string
                    issued_token_type:
                        description: urn:ietf:params:oauth:token-type:access_token
                        type: string
                    token_type:
                        description: Bearer
                        type: string
                    expires_in:
                        description: The remaining life time of the access token, in seconds
                        type: number
                  example:
                    access_token: 9ebe7940-6567-11e8-81d0-63274d553685
                    issued_token_type: urn:ietf:params:oauth:token-type:access_token
                    token_type: Bearer
                    expires_in: 600

        '400':
          description: "Error"
        
  '/token/verifications':
      post:
        tags:
          - Domain Authorization Interface
        summary: Verify the given access token with the authorization service.
        description: >-
          Verify the given access token with the authorization service.  The endpoint
          is usually called by the API Gateway or the micro-service itself to verify 
          the access token presented by the client before granting access to the
          requested resource/transaction.  The verification checks whether the access
          token was issued by this authorization service, has it expired, was it
          issued to the given client (client id) and user (uuid).  If a scope is
          given, it checks whether the scope is within the scope granted to this 
          access token.
        operationId: verifyAccessToken
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                          access_token:
                              description: The access token to verify
                              type: string
                          client_id:
                              description: The client's Id
                              type: string
                          uuid:
                            description: The uuid of the user 
                            type: string
                          scope:
                            description: >-
                              The scope of access requested, this may be a reference to a
                              protected domain/API/resource, must be a value contained in the
                              scope recorded by the authorization service for this access
                              token. If not provided, it will not be checked
                            type: string
                        example:
                          client_id: demowapp2
                          scope: openid
                          access_token: 9ebe7940-6567-11e8-81d0-63274d553685
                          uuid: fc7ab360-6557-11e8-935f-937a8aa9248

