#Default Parameters needed for a YAML file
openapi: 3.0.0
servers:
  - url: 'https://ndi.sg.io:3035/api/v1' #Real API link
    description: NDI API
    variables: {}
  - url: 'https://sandbox.ndi.io:3031/api/v1' #sandbox API link
    description: NDI API Sandbox
info:
  description: >-
    This is the API store where you can discover everything about integrating
    with the National Digital Identity (NDI) platform.  You can find out more
    about NDI at [http://ndi.sg.io/home](http://ndi.sg.io/home).  To try out the
    API, first go to the Authorization section to learn how to obtain an access
    token to access the API.
  version: 1.0.0
  title: National Digital Identity (NDI) - Form Factor Authenticator, Identity Verification
  termsOfService: 
  contact:
    email: support@ndi.gov.sg


externalDocs:
  description: Access technical reference for Form Factor Provider. (WIP)
  url: 'https://isomerpages.github.io/isomerpages-ndi/files/techref/ffproviders/ffprov'
  
#These are the tags for the side bar (the one on the left)
tags:
  - name: Form Factor Authenticator
    description: Form Factor Authenticator
  - name: Identity Verification
    description: Identity Verification

paths:
  '/auth/challenges/triggers':
    post:
      tags: 
       - Form Factor Authenticator
      summary: Send a signed challenge (JWS) to the target form factor
      description: >-
        This ASP is called by ASP to send a signed challenge (JWS) to the target
        form factor, in the form of an authentication request.
      operationId: triggerChallenge
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ff_auth_ref:
                  description: The unqiue reference identifying this FF authentication instance
                  type: string
                req_appname:
                  description: The requesting (client) app name, the FF auth service is to display this as requesting app in the authentication request message
                  type: string
                scope:
                  description: The requested scope, if provided, the FF auth services is to display this as request scope in the authentication request message
                  type: string
                uuid:
                  description: The uuid of the user
                  type: string
                ff_id:
                  description: The form factor id, this is form factor specific
                  type: string
                ff_attr:
                  description: An object containing the form factor attributes.The content is form factor-specific, which usually includes addressing info
                  type: object
                challenge:
                  description: The signed challenge in JWS format. The kid field in the JWS header is set to the ASP id,the FF auth service is to check the JWS signature with the ASP cert/public key to ensure it originated from an trusted ASP
                  type: string
                callback_uri:
                  description: The callback endpoint the target form factor is to called to return the signed response
                  type: string
              example:
                ff_auth_ref: "demowapp2:7dSchxNXMDiW"
                req_appname: "demowapp2"
                scope: "openid"
                uuid: "fc7ab360-6557-11e8-935f-937a8aa9248"
                ff_id: "fd8126e0-6557-11e8-969f-314ecfde78b4"
                ff_attr: >-
                 {"telegram":"","wp_sub":{"endpoint":"https://fcm.googleapis.com/fcm/send/f0rOBU3m9kc:APA91bHMk8wCF2fajLDkJfXsgHNIQiU_9f3Otpt97YLdWTb-vSp-gj5Ld21APCbf-_6Dm9apS_L-44Kcy43joqwiowfZwUjuvPIFIRL8cMQ4JsJFECdOK4p0C-fsU5El5AlWZ2wpvILM","expirationTime":null,"keys":{"p256dh":"BH0EAcB8iRcUYL8C9yiFsnPQjAZ86dpSfFOloPsTXs05_ROPf6rGFwUVmdkDbMG4ApBh8N7VLRXYv7d0k364Eus","auth":"VXcPOYsJkW7C73nmWodllQ"}}}
                challenge: "eyJ0eXAiOiJKV1QiLCJraWQiOiIxLjMuNi4xLjQuMS43MjcyMi4zLjEiLCJhbGciOiJFUzI1NiJ9.eyJjbGllbnRfaWQiOiJkZW1vd2FwcDIiLCJyZXFfdHlwZSI6ImF1dGhlbnRpY2F0aW9uIiwicmVxX3RpbWUiOjE1Mjc4Mjg5NDcxNTYsImNoYWxsZW5nZSI6ImZzZmVvdkM0d3JCZ1BuTk5oNDBYdS9qbEtwQVRMVkl2RmtkOGNUWVd1SVE9In0.e3QA3DGMGVUdWU9jstQ_I1NgwGdjE-e8n2rFAUaimgytxxNNevsR5p8sNF8n8-IvfQ-b2--ynyHLGgLvohpfQA"
                callback_uri: "https://ndi.sg.io:3033/api/v1/asp/responses"
      responses: 
        '200':
          description: "Authentication request successfully sent"
        '400':
          description: "Error"
